REFERENCE_TABLE = {
    'human': 13 - 1,
    'car': 21 - 1,
    'bus': 81 - 1,
    'truck': 84 - 1,
    'sky': 3 - 1,
    'wall': 1 - 1,
    'skyscraper': 49 - 1,
    'building': 2 - 1,
    'fence': 33 - 1,
    'railing': 39 - 1,
    'bannister': 96 - 1,
    'tree': 5 - 1,
    'grass': 10 - 1,
    'plant': 18 - 1,
    'flower': 67 - 1,
    'palm': 73 - 1,
    'chair': 20 - 1,
    'armchair': 31 - 1,
    'desk': 34 - 1,
    'pillar': 43 - 1,
    'signboard': 44 - 1,
    'path': 53 - 1,
    'stairway': 60 - 1,
    'bench': 70 - 1,
    'swivel': 76 - 1,
    'lamp': 88 - 1,
    'escalator': 97 - 1,
    'trafficlight': 137 - 1,
    'road': 7 - 1,
    'sidewalk': 12 - 1,
    'stairs': 54 - 1,
    'runway': 55 - 1,
}
GROUPS = {
    'human': ['human'],
    'car': ['car', 'bus', 'truck'],
    'sky': ['sky'],
    'green': ['tree', 'grass', 'plant', 'flower', 'palm'],
    'boundary': ['fence', 'railing', 'wall', 'bannister'],
    'building': ['skyscraper', 'building'],
    'constructor': ['pillar'],
    'lighting': ['lamp'],
    'pinterest': ['chair', 'armchair', 'desk', 'bench', 'swivel'],
    'sign': ['signboard', 'trafficlight'],
    'walkpath':
    ['escalator', 'sidewalk', 'stairs', 'runway', 'stairway', 'path'],
    'road': ['road']
}

INDEX_GROUPS_Numerator = {
    'SBI': ['boundary'],
    'SLI': ['lighting'],
    'SVI': ['constructor'],
    'TFI': ['human', 'car'],
    'PSI': ['walkpath'],
    'SI': ['sky'],
    'GVI': ['green'],
    'SAI': ['pinterest'],
    'EPI': ['building', 'green', 'boundary'],
    'EPI_D': ['walkpath', 'road'],
    'AI': ['walkpath', 'road'],
    'AI_D': ['boundary']
}
